apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftAPIServerConfig
storageConfig:
  urls:
  - https://etcd.openshift-etcd.svc:2379
apiServerArguments:
  audit-log-format:
  - json
  audit-log-maxbackup:
  - "10"
  audit-log-maxsize:
  - "100"
  audit-log-path:
  - /var/log/openshift-apiserver/audit.log
  audit-policy-file:
  - /var/run/configmaps/audit/policy.yaml
  shutdown-delay-duration:
  - 15s # this gives SDN 5s to converge after the worst readyz=false delay
  shutdown-send-retry-after:
  - "true"
servingInfo:
  bindNetwork: "tcp"
